/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_blink_live_blinkstreamlib_rtmp_RtmpClient */

#ifndef _Included_com_blink_live_blinkstreamlib_rtmp_RtmpClient
#define _Included_com_blink_live_blinkstreamlib_rtmp_RtmpClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_blink_live_blinkstreamlib_rtmp_RtmpClient
 * Method:    open
 * Signature: (Ljava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_com_blink_live_blinkstreamlib_rtmp_RtmpClient_open
  (JNIEnv * env, jobject thiz, jstring url_, jboolean isPublishMode);

/*
 * Class:     com_blink_live_blinkstreamlib_rtmp_RtmpClient
 * Method:    read
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_com_blink_live_blinkstreamlib_rtmp_RtmpClient_read
  (JNIEnv * env, jobject thiz,jlong rtmp, jbyteArray data_, jint offset, jint size);

/*
 * Class:     com_blink_live_blinkstreamlib_rtmp_RtmpClient
 * Method:    write
 * Signature: (J[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_blink_live_blinkstreamlib_rtmp_RtmpClient_write
  (JNIEnv * env, jobject thiz,jlong rtmp, jbyteArray data, jint size, jint type, jint ts);

/*
 * Class:     com_blink_live_blinkstreamlib_rtmp_RtmpClient
 * Method:    close
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_blink_live_blinkstreamlib_rtmp_RtmpClient_close
  (JNIEnv * env,jlong rtmp, jobject thiz);

/*
 * Class:     com_blink_live_blinkstreamlib_rtmp_RtmpClient
 * Method:    getIpAddr
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_blink_live_blinkstreamlib_rtmp_RtmpClient_getIpAddr
  (JNIEnv * env,jobject thiz,jlong rtmp);

#ifdef __cplusplus
}
#endif
#endif
